name: flutter_paystack_client
description: Paystack plugin with support for Web, Android and iOS
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_paystack: 1.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
